---
dependencies:
  - { role: geerlingguy.tomcat6 }

galaxy_info:
  author: geerlingguy
  description: Apache Solr for RHEL/CentOS and Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
