---
dependencies: []

galaxy_info:
  author: revagomes
  description: PHP PECL extension installation.
  company: "Taller Web Solutions"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - development
    - web
