---
# Required to change.
drupal_path: /home/vagrant/drupal/build
drupal_project_path: /home/vagrant/drupal
drupal_source: git@repogit.com/drupal/project.git
drupal_www_owner: vagrant
drupal_admin_password: ""
drupal_admin_email: admin@localhost.com
drupal_kw_name: new_drupal_project
drupal_kw_human_name: New Drupal project
# All properties are required for Database.
drupal_db_dump: ""
drupal_db:
  driver: mysql
  user: ""
  password: ""
  database: ""
  host: ""
  port: ""
  prefix: ""

# No need to change.
drupal_site_name: "New Drupal install"
drupal_project_branch: master
drupal_env: production
drupal_www_group: www-data
drupal_admin_name: admin
drupal_kw_source: https://github.com/kraftwagen/kraftwagen.git
drupal_kw_source_branch: master
drupal_kw_skeleton_source: git://github.com/kraftwagen/skeleton.git
drupal_kw_skeleton_branch: master
