---
- name: drupal kraftwagen update
  command: >
    drush kw-update
    chdir={{ drupal_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

- name: drupal kraftwagen manifests
  command: >
    drush kw-m
    chdir={{ drupal_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"