---
galaxy_info:
  author: Jarno Keskikangas
  description: Install nvm and Node.js.
  company: Leonidas
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
     - trusty
     - precise
     - quantal
     - raring
     - saucy
  - name: Debian
    versions:
     - wheezy
  categories:
  - development
  - packaging
  - web

dependencies: []
