- name: download
  sudo: true
  get_url: >
    url={{ direnv.bin_url }}
    sha256sum={{ direnv.bin_sha256 }}
    dest=/usr/local/bin/direnv
    owner=root
    group=root
    mode=0755

- name: install profile hook
  sudo: true
  copy: >
    content='eval "$(direnv hook bash)"'
    dest=/etc/profile.d/direnv.sh
    owner=root
    group=root
    mode=0644
