---

- name: Install Composer globally
  shell:  curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar {{ composer_path }} creates={{ composer_path }}
  tags: [composer, php]

- name: Create global .composer folder
  file: path={{ composer_user_home }}/.composer owner={{ composer_user }} state=directory
  tags: [composer, php]

- name: Create global composer.json file
  template: src=composer.j2 dest={{ composer_user_home }}/.composer/composer.json owner={{ composer_user }}
  when: composer_json != []
  notify:
   - composer global update
  tags: [composer, php]

- name: Add global composer bin directory to PATH
  lineinfile: dest={{composer_user_home}}/.bashrc line="export PATH=~/.composer/vendor/bin:$PATH"
  tags: [composer, php]

